name: check 

on:
 workflow_dispatch:
 

jobs:
  commithistory:
    name: action1
    runs-on: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v3
      - name: abc
        id: checkc
        run: |-
          p=$(git log -1|grep Update)
          echo $p
          if [[ $(git log -1 | grep yhb) ]]
          then
            echo ***commit history contains int1***
            exit 0
          fi
    
