name: check 

on:
 workflow_dispatch:
 pull_request:
   branches:
     - main
   types: [opened]

 

jobs:
  commithistory:
    name: action1
    runs-on: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v3
      - name: abc
        id: checkc
        run: |-
          p=$(git log -1)
          echo $p
          if [[ $(git log -1 | grep Update) ]]
          then
            echo ***commit history contains int1***
            exit 0
          else
            exit 1
          fi
    
