name: pjt

on:
 workflow_dispatch:

 pull_request:
   branches:
     - main
   types: [opened]

jobs:
  commithistory:
    name: action1
    runs-on: [ubuntu-latest]
    steps: 
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
     
  
      - name: Another step
        run: |
          echo "Branch: ${{ env.branch }}"
          echo "Sha: ${{ env.sha_short }}"
      - name: abc
        id: checkc
        run: |-
          if [[ $(git log -1 | grep Update) ]]
          then
            echo ***commit history contains int1***
            exit 0
          else
            exit 1
          fi
  
