name: pjt

on:
 workflow_dispatch:

 pull_request:
   branches:
     - main
   types: [opened]

jobs:
  commithistory:
    name: action1
    runs-on: [ubuntu-latest]
    steps: 
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: abc
        id: checkc
        run: |-
          echo "pr.ref = ${{github.event.pull_request.head.sha}}"
      - name: Print head git commit message
        id: get_head_commit_message
        run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"
  
