name: pjt

on:
 workflow_dispatch:

 pull_request:
   branches:
     - main
   types: [opened]

jobs:
  commithistory:
    name: action1
    runs-on: [ubuntu-latest]
    steps: 
      - name: Get repo
        uses: actions/checkout@v3
        
        
     
      - name: Get Head Commit Message
        id: get_head_commit_message
        run: |-
         p=$(git show -s --format=%s) 
         echo "Latest commit message on PR branch $p"
         if [[ $((git show -s --format=%s) | grep int1) ]]
         then
          echo "successfully completed first script"
          exit 0
         else
          exit 1
         fi
         
        
        
  
