name: pjt

on:
 workflow_dispatch:

 pull_request:
   branches:
     - main
   types: [opened]

jobs:
  commithistory:
    name: action1
    runs-on: [ubuntu-latest]
    steps: 
      - name: Get repo
        uses: actions/checkout@v3
        with:
          #ref: ${{ github.event.pull_request.head.sha }}
          ref: ${{ github.event.pull_request.head.sha }}
     
  
     
      - name: Get Head Commit Message
        id: get_head_commit_message
        run: 
         echo $(git show -s --format=%s)
        
        
  
